language: node_js
node_js:
    - '12'
install:
    - yarn install --frozen-lockfile --network-concurrency 1
script:
    - yarn test:mocha
cache:
    yarn: true
    directories:
        - ~/.cache/yarn
        - node_modules
notifications:
    email: true
